### ISSUE TITLE
[Feature] Listening to every message in a teams channel

### ISSUE THREAD

**Issue by DamienDoumer** [OfficeDev/BotBuilder-MicrosoftTeams-dotnet#30]
**Description:**
We are building a support bot which runs on Microsoft Teams Only.
Actually our bot only receives messages which contain a mention to it.
But the ideal scenario will be to listen to every message sent into the specific channel.

**Alternatives**
I went around Microsoft Docs, and found out it was not actually possible to implement this later scenario. 
So actually, the first scenario of mentioning the bot every time is the only solution.

**Comment by RamjotSingh** [comment]
Bots can only receive messages in which they are at mentioned. If you want access to every message in the channel, I would recommend looking to Graph APIs. https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=cs. We are working on making it easy to just get new messages instead of polling a channel. But all those APIs will be supported through Microsoft Graph.

**Comment by DamienDoumer** [comment]
Ok, got it @RamjotSingh
